start -> code
code -> presumably_comment: /
presumably_comment -> ml_comment: *
presumably_comment -> sl_comment: /
presumably_comment -> quote: \"
presumably_comment -> code: char - * /, \"
code -> quote: \"
quote -> code: \"
code -> code: char - /, \"
ml_comment -> ml_comment: char - *, /
ml_comment -> presumably_stop_ml_comment: *
presumably_stop_ml_comment -> code: /
presumably_stop_ml_comment -> quote: \"
presumably_stop_ml_comment -> ml_comment: char - /, \"

sl_comment -> code: \\n
sl_comment -> presumably_sl_comment_error: /
sl_comment -> sl_comment: char - \\n, /
presumably_sl_comment_error -> comment_error: /, *
presumably_sl_comment_error -> sl_comment: char - /, *

ml_comment -> presumably_ml_comment_error: /
presumably_ml_comment_error -> comment_error: /, *
presumably_ml_comment_error -> ml_comment: char - /, *
