void -> 'signed char'
'signed char' -> 'signed short'
'unsigned char' -> 'unsigned short'
void -> 'unsigned char'
'signed short' -> 'signed int'
'unsigned short' -> 'unsigned int'
'signed int' -> 'signed long'
'unsigned int' -> 'unsigned long'
'signed long' -> float
'unsigned long' -> float
'float' -> double
double -> 'long double'
'long double' -> 'long long double'
